### ISSUE TITLE
Remove font-size mixin

### ISSUE THREAD

**Issue by dylanbaumann** [aiganebraska/wordpress-starter#3]
# Issue

The mixin generates a `rem` value for font size as well as a `px` fallback. The `px` fallback is only needed in Internet Explorer 8 and before, which this theme does not support by default.

### Notes

There are a few places throughout the repo this will need removed, namely mixins, buttons, and forms. The new method for defining font sizes is outlined below.

Current Method:
```css
// Initial
h1 {
    @include font-size(4.2);
}

// Returns
h1 {
    font-size: 42px; 
    font-size: 4.2rem;
}
```

New Method:
```css
// Initial and Return
h1 {
    font-size: 4.2rem;
}
